"""
FEF Arealmodell register og NS 3457-4 romfunksjoner med tillatte verdier.
"""

FEF_REGISTER = [
    {"Romtype": "A",  "Romtype_beskrivelse": "Behandlingsrom",       "Romkategori": "Behandling"},
    {"Romtype": "A",  "Romtype_beskrivelse": "Behandlingsrom",       "Romkategori": "Røntgen"},
    {"Romtype": "A",  "Romtype_beskrivelse": "Behandlingsrom",       "Romkategori": "Venterom"},
    {"Romtype": "B",  "Romtype_beskrivelse": "Spesialrom",           "Romkategori": "Lab (Støvfri lab, Lab, Steril)"},
    {"Romtype": "C",  "Romtype_beskrivelse": "Rom Ansatte",          "Romkategori": "Kontor"},
    {"Romtype": "C",  "Romtype_beskrivelse": "Rom Ansatte",          "Romkategori": "Personalrom"},
    {"Romtype": "C",  "Romtype_beskrivelse": "Rom Ansatte",          "Romkategori": "Garderober og toaletter"},
    {"Romtype": "D",  "Romtype_beskrivelse": "Pasientrom/fellesrom", "Romkategori": "Venterom"},
    {"Romtype": "D",  "Romtype_beskrivelse": "Pasientrom/fellesrom", "Romkategori": "Garderober og toaletter"},
    {"Romtype": "E1", "Romtype_beskrivelse": "Teknisk drift",        "Romkategori": "IKT"},
    {"Romtype": "E1", "Romtype_beskrivelse": "Teknisk drift",        "Romkategori": "Renhold"},
    {"Romtype": "E1", "Romtype_beskrivelse": "Teknisk drift",        "Romkategori": "Drift (Motorrom, Garasje)"},
    {"Romtype": "E2", "Romtype_beskrivelse": "Tekniske rom",         "Romkategori": "Tekniske rom"},
    {"Romtype": "F1", "Romtype_beskrivelse": "Konstruksjonsareal",   "Romkategori": "Konstruksjonsareal"},
    {"Romtype": "F2", "Romtype_beskrivelse": "Trafikkareal",         "Romkategori": "Trafikkareal"},
]

NS3457_REGISTER = [
    (111, "Soverom"),
    (112, "Dagligrom"),
    (113, "Venterom"),
    (114, "Veranda"),
    (121, "Bad"),
    (122, "Toalett"),
    (123, "UU-toalett"),
    (124, "Stellerom"),
    (125, "Omkledningsrom"),
    (126, "Dusjsone"),
    (127, "Badstue"),
    (128, "Forrom med vask"),
    (131, "Sikringsrom"),
    (132, "Tilfluktsrom"),
    (141, "Forvaringsrom"),
    (211, "Kontor"),
    (212, "Møterom"),
    (213, "Mottakelsesrom"),
    (214, "Forretningslokale"),
    (215, "Undervisningsrom"),
    (216, "Studierom"),
    (217, "Overvåkningsrom"),
    (218, "Observasjonsrom"),
    (219, "Kontrollrom"),
    (221, "Verksted"),
    (222, "Kjøkken"),
    (223, "Produksjonsrom"),
    (224, "Funksjonsstøtterom"),
    (225, "Kontorstøtterom"),
    (226, "Vaskerom"),
    (231, "Idrettshall"),
    (232, "Svømmehall"),
    (233, "Ishall"),
    (234, "Treningsrom"),
    (235, "Øvingsrom"),
    (236, "Scenerom"),
    (237, "Lekerom"),
    (241, "Spiserom"),
    (242, "Bibliotek"),
    (243, "Sal"),
    (244, "Utstillingsrom"),
    (245, "Livssynsrom"),
    (251, "Våtlaboratorium"),
    (252, "Tørrlaboratorium"),
    (253, "Medisinsk laboratorium"),
    (261, "Medisinsk undersøkelsesrom"),
    (262, "Medisinsk behandlingsrom"),
    (263, "Kombinert medisinsk undersøkelses- og behandlingsrom"),
    (264, "Ikke-medisinsk undersøkelses og behandlingsrom"),
    (311, "Avfallsrom"),
    (312, "Rom for farlige stoffer og eksplosiver"),
    (313, "Medisinsk lager"),
    (314, "Råvarelager"),
    (315, "Mat- og drikkelager"),
    (316, "Ferdigvarelager"),
    (321, "Tøy- og skolager"),
    (322, "Inventarlager"),
    (323, "Redskapslager"),
    (324, "Maskinlager"),
    (325, "Apparatlager"),
    (326, "Transportmiddellager"),
    (327, "Våpen- og ammunisjonslager"),
    (328, "Rom for kontaminerte klær"),
    (331, "Dokumentarkiv"),
    (332, "Hvelv"),
    (341, "Morsrom"),
    (351, "Oppstillingsplass"),
    (352, "Ladestasjon"),
    (361, "Bur"),
    (362, "Bås"),
    (363, "Stall"),
    (364, "Oppdrettsrom"),
    (365, "Akvarium"),
    (366, "Terrarium"),
    (371, "Veksthus"),
    (411, "VVS-teknisk rom"),
    (412, "Elkraftrom"),
    (413, "Tele- og automatiseringsrom"),
    (414, "Rom for teknisk interntransport"),
    (421, "Servicegang"),
    (422, "Sjakt"),
    (423, "Kanal"),
    (431, "Krypkjeller"),
    (432, "Lyssjakt"),
    (511, "Adkomstrom"),
    (512, "Sluse"),
    (513, "Korridor"),
    (514, "Trapperom"),
    (515, "Heissjakt"),
    (611, "Reserveareal"),
    (612, "Ikke disponibelt areal"),
    (613, "Avstengt areal"),
]

# Oppslag
NS3457_KODE_TIL_BESKRIVELSE = {kode: beskrivelse for kode, beskrivelse in NS3457_REGISTER}
ROMTYPE_TIL_BESKRIVELSE = {r["Romtype"]: r["Romtype_beskrivelse"] for r in FEF_REGISTER}
GYLDIGE_KATEGORIER = {}
for r in FEF_REGISTER:
    GYLDIGE_KATEGORIER.setdefault(r["Romtype"], []).append(r["Romkategori"])
